/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.ConexionMariaDB;
import Controlador.ControladorUsuario;
import Controlador.ObtenerFechaHora;
import Modelo.Usuario;
import java.awt.BorderLayout;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Domingo Luna
 */
public class FrmPrincipal extends javax.swing.JFrame {
    ConexionMariaDB conexionMariaDB;
    ControladorUsuario controladorUsuario;
    PnlEntradaSemiterminado pnlInvSemiterminado;
    PnlProductoProceso pnlProductoProceso;
    PnlSaldos pnlSaldos;
    PnlPedacera pnlPedacera;
    PnlPrincipal pnlPrincipal;
    
    
    private final String imagen="/ima/computer.png";
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() throws Exception 
    {
        initComponents();
        
        //Colocar icono de la aplicación
        Image ico=new ImageIcon(getClass().getResource("/ima/esmar.png")).getImage();
        setIconImage(ico);
        
        //Titulo de la aplicación
        this.setTitle("Control de inventarios y ventas V.0.1");
        inicializar();
    }
    
    
    //Método que se invica al inicializar el sistema, inicializa todas las clases a utilizar
    public void inicializar() throws Exception
    {
        conexionMariaDB=new ConexionMariaDB();
        controladorUsuario=new ControladorUsuario(conexionMariaDB);
        pnlProductoProceso=new PnlProductoProceso();
        pnlInvSemiterminado=new PnlEntradaSemiterminado();
        pnlSaldos=new PnlSaldos();
        pnlPedacera=new PnlPedacera();
        
        //Inicializamos las propiedades del dialogo:
        dlgLogin.setSize(560, 322);
        dlgLogin.setPreferredSize(dlgLogin.getSize());
        dlgLogin.setLocationRelativeTo(null);
        dlgLogin.setAlwaysOnTop(true);
        dlgLogin.setVisible(true);
    }
    
    //Metodo para poner la fecha del sistema traida del servidor
    public void DateLabel()
    {
        ObtenerFechaHora of=new ObtenerFechaHora();
        lblFecha.setText(of.ObtenerFechaHora());
    }
        
    
    private void validarUsuario()
    {
        Usuario u = new Usuario();
        u.setUserName(txtUserName.getText());
        u.setPassword(new String(ptxtPassword.getPassword()));
        
        try
        {
            if (controladorUsuario.validarUsuario(u))
            {
                dlgLogin.setVisible(false);
                this.setVisible(true);
                pnlPrincipal=new PnlPrincipal();
                pnlPrincipalx.removeAll();        
                pnlPrincipalx.add(pnlPrincipal, BorderLayout.CENTER);
                pnlPrincipalx.paintAll(pnlPrincipal.getGraphics());
                DateLabel();
                lblNombreEmpleado.setText(u.getNombre());
                lblIdUsuario.setText(u.getIdUsuario());
                lblTipoUsuario.setText(u.getTipo());
                lblTipoUsuario.setVisible(false);
                
                if (lblTipoUsuario.getText().equals("Sistemas"))
                {
                    btnRecepcionSemiterminado.setVisible(false);
                    btnProductoProceso.setVisible(false);
                }
            }
            else
                JOptionPane.showMessageDialog(dlgLogin, "Datos incorrectos", "Error de Login", JOptionPane.ERROR_MESSAGE);
        }
        catch (Exception e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(dlgLogin, "Error de conexion de datos", "Error de conexion", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgLogin = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        ptxtPassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnRecepcionSemiterminado = new javax.swing.JButton();
        btnProductoProceso = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnSaldos = new javax.swing.JButton();
        btnPedacera = new javax.swing.JButton();
        pnlPrincipalx = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblVentana = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNombreEmpleado = new javax.swing.JLabel();
        lblIdUsuario = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblFecha2 = new javax.swing.JLabel();
        lblTipoUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        dlgLogin.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        dlgLogin.setTitle("Login");
        dlgLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sistema para el control de inventarios y ventas");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Contraseña:");

        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Usuario:");

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/door.png"))); // NOI18N
        jButton5.setText("Entrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/cross_1.png"))); // NOI18N
        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        ptxtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ptxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptxtPasswordActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/logoEsmar.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/status_online.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/lock.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6))
                            .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(ptxtPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel9)))
                .addContainerGap(161, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(ptxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        dlgLogin.getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1200, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/logoEsmar.png"))); // NOI18N

        lblFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFecha.setText("Fecha");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/house.png"))); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnRecepcionSemiterminado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRecepcionSemiterminado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/cuero.png"))); // NOI18N
        btnRecepcionSemiterminado.setText("Recepción Semiterminado");
        btnRecepcionSemiterminado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRecepcionSemiterminado.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRecepcionSemiterminado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecepcionSemiterminadoActionPerformed(evt);
            }
        });

        btnProductoProceso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnProductoProceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/cueroProceso.png"))); // NOI18N
        btnProductoProceso.setText("Producto en proceso");
        btnProductoProceso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProductoProceso.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnProductoProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoProcesoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Menu");

        btnSaldos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSaldos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/cueroProceso.png"))); // NOI18N
        btnSaldos.setText("Saldos");
        btnSaldos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSaldos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSaldos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaldosActionPerformed(evt);
            }
        });

        btnPedacera.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPedacera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/cueroProceso.png"))); // NOI18N
        btnPedacera.setText("Pedacera");
        btnPedacera.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPedacera.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPedacera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedaceraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRecepcionSemiterminado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnProductoProceso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(btnSaldos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPedacera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRecepcionSemiterminado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProductoProceso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaldos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPedacera)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pnlPrincipalx.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipalx.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlPrincipalx.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblVentana.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblVentana.setText("Inicio");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVentana)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVentana)
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Bienvenido:");

        lblNombreEmpleado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombreEmpleado.setText("Nombre empleado");

        lblIdUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIdUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIdUsuario.setText("IdUsuario");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Id. Usuario:");

        lblFecha2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFecha2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFecha2.setText("Fecha:");

        lblTipoUsuario.setText("Tipo usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 338, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel12)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblIdUsuario)
                                .addGap(66, 66, 66))
                            .addComponent(lblNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTipoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFecha2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFecha)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPrincipalx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNombreEmpleado, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdUsuario)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFecha)
                            .addComponent(lblFecha2)
                            .addComponent(lblTipoUsuario))
                        .addGap(5, 5, 5)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlPrincipalx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/page.png"))); // NOI18N
        jMenu1.setText("Archivo");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/cross.png"))); // NOI18N
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/information.png"))); // NOI18N
        jMenu2.setText("Acerca de");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnProductoProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoProcesoActionPerformed
        try {
            pnlProductoProceso=new PnlProductoProceso();
        } catch (Exception ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        pnlPrincipalx.removeAll();
        pnlPrincipalx.add(pnlProductoProceso, BorderLayout.CENTER);
        pnlPrincipalx.paintAll(pnlProductoProceso.getGraphics());
        
        if (lblTipoUsuario.getText().equals("Produccion"))
        {
            pnlProductoProceso.btnAgregarEntrada1.setVisible(false);
            pnlProductoProceso.btnAgregarSeleccionar.setVisible(false);
            pnlProductoProceso.btnAgregarPesar.setVisible(false);
            pnlProductoProceso.btnBaja.setVisible(false);
        }
        
        lblVentana.setText("Producto en proceso");
        ImageIcon ico=new ImageIcon(".\\src\\ima\\cueroProceso.png");
        Icon icono = new ImageIcon(ico.getImage()); 
        lblVentana.setIcon(ico);
    }//GEN-LAST:event_btnProductoProcesoActionPerformed

    private void btnRecepcionSemiterminadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecepcionSemiterminadoActionPerformed
        try {
            pnlInvSemiterminado=new PnlEntradaSemiterminado();
        } catch (Exception ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        pnlPrincipalx.removeAll();
        pnlPrincipalx.add(pnlInvSemiterminado, BorderLayout.CENTER);
        pnlPrincipalx.paintAll(pnlInvSemiterminado.getGraphics());
        
        if (lblTipoUsuario.getText().equals("Produccion"))
        {
            pnlInvSemiterminado.btnAgregarEntrada.setVisible(false);
        }
        
        lblVentana.setText("Recepción semiterminado");
        ImageIcon ico=new ImageIcon(".\\src\\ima\\cuero.png");
        Icon icono = new ImageIcon(ico.getImage()); 
        lblVentana.setIcon(ico);
        
    }//GEN-LAST:event_btnRecepcionSemiterminadoActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        pnlPrincipal=new PnlPrincipal();
        pnlPrincipalx.removeAll();
        pnlPrincipalx.add(pnlPrincipal, BorderLayout.CENTER);
        pnlPrincipalx.paintAll(pnlPrincipal.getGraphics());
        
        lblVentana.setText("Inicio");
        ImageIcon ico=new ImageIcon(".\\src\\ima\\house.png");
        Icon icono = new ImageIcon(ico.getImage()); 
        lblVentana.setIcon(ico);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        validarUsuario();
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        validarUsuario();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void ptxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptxtPasswordActionPerformed
        validarUsuario();
    }//GEN-LAST:event_ptxtPasswordActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        JOptionPane.showMessageDialog(null, "'Control de inventarios de producto semiterminado V.1.0' \n"
                                           + "Noviembre 2015\n\nDesarrollado por: \nIng. Cesar Domingo Luna Gutiérrez \n\n"
                                           + "Dudas, comentarios o reportes de errores: \n"
                                           + "mingo.utl@gmail.com, domingo.luna@esmar.com.mx", "Acerca de...", 
                                           JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void btnSaldosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldosActionPerformed
        pnlPrincipalx.removeAll();
        pnlPrincipalx.add(pnlSaldos, BorderLayout.CENTER);
        pnlPrincipalx.paintAll(pnlSaldos.getGraphics());
        
        if (lblTipoUsuario.getText().equals("Produccion"))
        {
            pnlSaldos.btnAgregar.setVisible(false);
            pnlSaldos.btnBaja.setVisible(false);
        }
        
        lblVentana.setText("Saldos de producto");
        ImageIcon ico=new ImageIcon(".\\src\\ima\\cuero.png");
        Icon icono = new ImageIcon(ico.getImage()); 
        lblVentana.setIcon(ico);
    }//GEN-LAST:event_btnSaldosActionPerformed

    private void btnPedaceraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedaceraActionPerformed
        pnlPrincipalx.removeAll();
        pnlPrincipalx.add(pnlPedacera, BorderLayout.CENTER);
        pnlPrincipalx.paintAll(pnlPedacera.getGraphics());
        
        if (lblTipoUsuario.getText().equals("Produccion"))
        {
            pnlPedacera.btnAgregar.setVisible(false);
            pnlPedacera.btnBaja.setVisible(false);
        }
        
        lblVentana.setText("Pedacera de producto");
        ImageIcon ico=new ImageIcon(".\\src\\ima\\cuero.png");
        Icon icono = new ImageIcon(ico.getImage()); 
        lblVentana.setIcon(ico);
    }//GEN-LAST:event_btnPedaceraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmPrincipal().setLocationRelativeTo(null);
                } catch (Exception ex) {
                    Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnPedacera;
    private javax.swing.JButton btnProductoProceso;
    private javax.swing.JButton btnRecepcionSemiterminado;
    private javax.swing.JButton btnSaldos;
    private javax.swing.JDialog dlgLogin;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFecha2;
    public static javax.swing.JLabel lblIdUsuario;
    private javax.swing.JLabel lblNombreEmpleado;
    private javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JLabel lblVentana;
    private javax.swing.JPanel pnlPrincipalx;
    private javax.swing.JPasswordField ptxtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
